DROP TABLE IF EXISTS owners_cars;

CREATE TABLE owners_cars (
    OID INTEGER UNSIGNED NOT NULL,
    VID varchar(20) NOT NULL,
    current_price DECIMAL UNSIGNED NOT NULL,
    PRIMARY KEY(OID, VID),
    FOREIGN KEY (OID) REFERENCES owners(user_id),
    FOREIGN KEY (VID) REFERENCES cars(vin)
);